
name: CI

# Controls when the action will run.
on: [push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Setup Java Env
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt' # See 'Supported distributions' for available options
          java-version: '11'
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
      - name: Build the app
        run: ./gradlew --no-daemon build
      - name: Test the app
        run: ./gradlew --no-daemon test